### ISSUE TITLE
"application protocol failed to receive SSL data" during upload

### ISSUE THREAD

**Issue by jonozzz** [pgjones/quart#41]
```
cd examples/http2_push
#edit / route to accept POST
#@app.route('/', methods=['POST'])
QUART_APP=http2_push quart run
```
Now create a payload file:
```
dd if=/dev/urandom of=payload count=10000
```
Do POST to /:
```
curl -d @payload -vsk https://127.0.0.1:5000/
```

Server console shows this error and then connection hangs:
```
application protocol failed to receive SSL data
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f1358bdeac8>
transport: <_SelectorSocketTransport fd=8 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "lib/python3.7/asyncio/sslproto.py", line 541, in data_received
    self._app_protocol.data_received(chunk)
  File "xyz/hypercorn/hypercorn/asyncio/run.py", line 59, in data_received
    self._server.data_received(data)
  File "xyz/hypercorn/hypercorn/asyncio/h2.py", line 100, in data_received
    self.handle_events(events)
  File "xyz/hypercorn/hypercorn/asyncio/h2.py", line 126, in handle_events
    self.streams[event.stream_id].append(event.data)
KeyError: 1
```

**Comment by pgjones** [comment]
I think quart should be responding with a 400 here, as the message is malformed. (Encoding can't possibly be correct). I've partially fixed this in f311f577e0b9f67951420d45437184caf082ea7d - does it resolve your issue?

**Comment by jonozzz** [comment]
Yes, partially. The exception is gone but curl still hangs at the end.

**Comment by pgjones** [comment]
Hmm, thats strange I get a 400 response. Does the server still respond to requests? Are there any useful logs?

**Comment by jonozzz** [comment]
No errors, and I enabled debug logging. All I see are some debug statements from hpack.
For this to happen the uploaded payload needs to be fairly large >5MB, not sure where exactly is the threshold but a 2MB file doesn't cause the lockup.

**Comment by pgjones** [comment]
I can't reproduce this sadly, what does your route function do?

**Comment by jonozzz** [comment]
This is my app:
```
@app.route('/', methods=['POST', 'GET'])
async def index():
    return 'Hi'

def run(port):
    base_path = '.'
    certfile = os.path.join(base_path, 'dut.stbl.int.cr')
    keyfile = os.path.join(base_path, 'dut.stbl.int.ke')

    config = Config()
    config.certfile = certfile
    config.keyfile = keyfile
    config.bind = ["0.0.0.0:%d" % port]

    loop = asyncio.get_event_loop()
    loop.run_until_complete(serve(app, config))
```
Note that to repro you need a fairly large file (>5MB) to upload.

**Comment by pgjones** [comment]
I've managed to track this down, [this](https://gitlab.com/pgjones/hypercorn/commit/39041f27040edec88dd4840122812a96d443e7d9) should fix the issue in Hypercorn and there is another in Quart whereby a `RequestEntityTooLarge(413)` is raised but not dealt with.

**Comment by pgjones** [comment]
This is the second fix, 3475a87eab6f1ab434f52382efdbbae607e2eb1f

**Comment by jonozzz** [comment]
Ok, just pulled the changes and it doesn't hang anymore. Curl is now getting a "HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)" and no error on the the server side. Shouldn't I see a 431 error thrown back to the client?

**Comment by pgjones** [comment]
You have to trigger access to the request body for an error to be raised (try adding `await request.get_data()`). Otherwise it will just close after sending the request - this should be fine though.

**Comment by jonozzz** [comment]
Ok, got it now. I had to set the request limit to a low value ```app.config['MAX_CONTENT_LENGTH'] = 1024``` and then do await the get_data(). Without the get_data() it'll still hang at the end of the response.

**Comment by pgjones** [comment]
Can you update Hypercorn to 0.5.1 and try it? It shouldn't hang then,

**Comment by jonozzz** [comment]
I did. It must be something in the random payload I generated. If I don't do a get_data(), set the max_content_length to say...300 and then upload 400 bytes (of text, not garbage) I get a 200 back with the response - it doesn't even check for max_content_length. It looks like that path is taken only when I await for get_data().

**Comment by pgjones** [comment]
Yea, that is true. If the route does nothing with the body Quart won't check it (it will accumulate in memory though) - however if the route does nothing with the body it should complete in a timely fashion and then close the connection (or at least stop receiving the body). 

It is a bit convoluted, sadly.

**Comment by pgjones** [comment]
I think this is good to close, please reopen and let me know what I'm missing if not.
